#!/usr/bin/env zsh

BREW="/opt/homebrew"

# Aliases
alias b="bundle"
alias c="git create-branch"
alias flush-cache="sudo killall -HUP mDNSResponder"
alias m="rake db:migrate db:rollback && rake db:migrate db:test:prepare"
alias mkdir="mkdir -p"
alias vim="nvim"

# Editor
export VISUAL=nvim
export EDITOR=$VISUAL

# History
HISTFILE=~/.zhistory
HISTSIZE=500
SAVEHIST=500

# https://docs.brew.sh/Analytics
unset HOMEBREW_NO_ANALYTICS

# fzf to find files, ag to search files
if [ -e "$BREW/opt/fzf/shell" ]; then
  source "$BREW/opt/fzf/shell/key-bindings.zsh"
fi
export FZF_DEFAULT_COMMAND='ag --hidden --nocolor -g ""'

# Color
autoload -U colors
colors
export CLICOLOR=1

# Prompt
function git_prompt_info() {
  current_branch=$(git current-branch 2> /dev/null)
  if [[ -n $current_branch ]]; then
    echo " %{$fg_bold[green]%}$current_branch%{$reset_color%}"
  fi
}
setopt promptsubst
if ! env | grep -q '^PS1='; then
  PS1='%{$fg_bold[blue]%}%c%{$reset_color%}$(git_prompt_info) %# '
fi

# Completion
fpath=(~/.zsh $fpath)
autoload -Uz compinit
compinit -u

# Bat
export BAT_THEME="TwoDark"

# Go
PATH="$BREW/go/bin:$HOME/go/bin:$PATH"

# Ruby
export RUBYOPT="--enable-yjit"
PATH="$HOME/.rubies/ruby-3.3.0/bin:$PATH"

# Homebrew
PATH="$BREW/bin:$PATH"

# Node
PATH="$BREW/opt/node@20/bin:$PATH"

# Postgres
export PGUSER=postgres
PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"

# Laptop
export LAPTOP="$HOME/laptop"
PATH="$LAPTOP/bin:$PATH"

# Current project
PATH=".git/safe/../../bin:$PATH"

export PATH
