let mapleader = " "   " Spacebar

set autoindent
set autowrite         " Automatically :write before running commands
set backspace=2       " Backspace deletes like most programs in insert mode
set cmdheight=2
set complete+=kspell  " Include spellfile in completion results
set diffopt+=vertical " Always use vertical diffs
set encoding=utf-8
set expandtab
set exrc              " http://andrew.stwrt.ca/posts/project-specific-vimrc/
set hidden            " TextEdit might fail if hidden is not set
set history=50
set incsearch
set laststatus=2      " Always display status line
set list listchars=tab:»·,trail:·,nbsp:·
set modelines=0       " Disable modelines as a security precaution
set mouse=
set nobackup
set nojoinspaces      " Use one space, not two, after punctuation
set nomodeline        " Disable modelines as a security precaution
set noswapfile
set nowritebackup
set number
set numberwidth=5
set ruler             " Ahow cursor position all the time
set shiftround
set shiftwidth=2
set shortmess+=c      " Don't pass messages to |ins-completion-menu|
set showcmd           " Display incomplete commands
set signcolumn=yes
set splitbelow
set splitright
set tabstop=2
set textwidth=80
set updatetime=300

if &compatible
  set nocompatible
end

" Open vim-plug without a vertical split
let g:plug_window='enew'

call plug#begin('~/.vim/plugged')
  " Neovim
  Plug 'neovim/nvim-lspconfig'
  Plug 'hrsh7th/cmp-nvim-lsp'
  Plug 'hrsh7th/cmp-buffer'
  Plug 'hrsh7th/cmp-path'
  Plug 'hrsh7th/cmp-cmdline'
  Plug 'hrsh7th/nvim-cmp'
  Plug 'hrsh7th/cmp-vsnip'
  Plug 'hrsh7th/vim-vsnip'

  " :help ale
  Plug 'dense-analysis/ale'

  " :help projectionist, .projections.json, :A
  Plug 'tpope/vim-projectionist'

  " Fuzzy-finding :Ag, :Commits, :Files
  Plug '/opt/homebrew/opt/fzf'
  Plug 'junegunn/fzf.vim'

  " :TestFile, :TestNearest
  Plug 'janko-m/vim-test'

  " Comment/uncomment lines and selections with <gcc>
  Plug 'tomtom/tcomment_vim'

  " Filesystem, :Rename :Gblame
  Plug 'pbrisbin/vim-mkdir'
  Plug 'tpope/vim-eunuch'
  Plug 'tpope/vim-fugitive'

  " Frontends
  Plug 'evanleck/vim-svelte'
  Plug 'leafgarland/typescript-vim'
  Plug 'mxw/vim-jsx'
  Plug 'pangloss/vim-javascript'

  " Backends
  Plug 'vim-crystal/vim-crystal'
  Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
  Plug 'tpope/vim-rails'
  Plug 'vim-ruby/vim-ruby'
call plug#end()

" When reading a buffer, jump to last known cursor position except for
" commit messages, when position is invalid, or inside an event handler.
augroup lastcursorposition
  autocmd!

  autocmd BufReadPost *
    \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif
augroup END

" Lint with ALE
augroup ale
  autocmd!

  autocmd VimEnter *
    \ let g:ale_lint_on_enter = 1 |
    \ let g:ale_lint_on_text_changed = 0
augroup END

" Disable spelling by default, enable per-filetype
autocmd BufRead setlocal nospell

" Fuzzy-find files
nnoremap <C-p> :Files<CR>
let g:fzf_layout = { 'window': { 'width': 0.95, 'height': 0.9 } }

" Search file contents
nnoremap \ :Ag<SPACE>
set grepprg=ag\ --nogroup\ --nocolor

" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

" Switch between the last two files
nnoremap <Leader><Leader> <C-^>

" Run tests https://github.com/vim-test/vim-test#kitty-strategy-setup
nnoremap <silent> <Leader>t :TestFile<CR>
nnoremap <silent> <Leader>s :TestNearest<CR>
let g:test#strategy = "neovim"
let g:test#neovim#start_normal = 1
let g:test#echo_command = 0

" Move between windows
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Colors
hi clear
if exists("syntax_on")
  syntax reset
endif

" Show all syntax groups
" :so $VIMRUNTIME/syntax/hitest.vim

" Black
hi IncSearch      ctermfg=16  ctermbg=189
hi Label          ctermfg=16
hi MatchParen     ctermfg=16  ctermbg=189
hi Normal         ctermfg=16  ctermbg=231
hi Pmenu          ctermfg=16  ctermbg=231
hi PmenuSbar      ctermfg=16  ctermbg=231
hi PmenuThumb     ctermfg=16  ctermbg=231
hi Search         ctermfg=16  ctermbg=189
hi Statement      ctermfg=16
hi StorageClass   ctermfg=16
hi Structure      ctermfg=16
hi TypeDef        ctermfg=16
hi Underlined     ctermfg=16 cterm=NONE
hi rubyDefine     ctermfg=16
hi rubyMacro      ctermfg=16
hi rubyValidation ctermfg=16

" Light gray
hi Comment        ctermfg=250
hi Cursor         ctermfg=250 ctermbg=238
hi CursorLineNr   ctermfg=250 ctermbg=253
hi Error          ctermfg=250 ctermbg=231
hi Folded         ctermfg=250 ctermbg=255
hi Ignore         ctermfg=250
hi LineNr         ctermfg=250 ctermbg=255
hi NonText        ctermfg=250 ctermbg=255
hi PmenuSel       ctermfg=250 ctermbg=238
hi PreProc        ctermfg=250
hi Special        ctermfg=250 ctermbg=231
hi SpecialKey     ctermfg=250 ctermbg=231
hi StatusLine     ctermfg=250 ctermbg=255
hi StatusLineNC   ctermfg=250 ctermbg=255
hi TabLine        ctermfg=250 ctermbg=253
hi TabLineFill    ctermfg=250 ctermbg=253
hi TabLineSel     ctermfg=250
hi Todo           ctermfg=250 ctermbg=231
hi VertSplit      ctermfg=250 ctermbg=250
hi Visual         ctermfg=250 ctermbg=61
hi VisualNOS      ctermfg=250 ctermbg=24
hi gitCommitDiff  ctermfg=250

" Pink
hi DiffDelete     ctermfg=161
hi Directory      ctermfg=161
hi ErrorMsg       ctermfg=161 ctermbg=231
hi Function       ctermfg=161 ctermbg=231
hi ModeMsg        ctermfg=161
hi MoreMsg        ctermfg=161
hi SpecialKey     ctermfg=161
hi Search         ctermfg=161 ctermbg=231
hi String         ctermfg=161
hi Title          ctermfg=161
hi WarningMsg     ctermfg=161
hi diffRemoved    ctermfg=161
hi rubySymbol     ctermfg=161

" Turquoise
hi Constant        ctermfg=30
hi DiffAdd         ctermfg=30 ctermbg=194
hi Identifier      ctermfg=30
hi Number          ctermfg=30
hi Special         ctermfg=30
hi Type            ctermfg=30
hi WildMenu        ctermfg=30 ctermbg=60
hi diffAdded       ctermfg=30
