let mapleader = " "   " Spacebar

set autoindent
set autowrite         " Automatically :write before running commands
set backspace=2       " Backspace deletes like most programs in insert mode
set cmdheight=2
set complete+=kspell  " Include spellfile in completion results
set diffopt+=vertical " Always use vertical diffs
set encoding=utf-8
set expandtab
set exrc              " http://andrew.stwrt.ca/posts/project-specific-vimrc/
set fillchars=eob:\   " Hide ~ end-of-file markers
set hidden            " TextEdit might fail if hidden is not set
set history=50
set incsearch
set laststatus=2      " Always display status line
set list listchars=tab:»·,trail:·,nbsp:·
set modelines=0       " Disable modelines as a security precaution
set mouse=
set nobackup
set nojoinspaces      " Use one space, not two, after punctuation
set nomodeline        " Disable modelines as a security precaution
set noswapfile
set nowritebackup
set ruler             " Ahow cursor position all the time
set shiftround
set shiftwidth=2
set shortmess+=c      " Don't pass messages to |ins-completion-menu|
set showcmd           " Display incomplete commands
set signcolumn=yes
set splitbelow
set splitright
set tabstop=2
set termguicolors
set textwidth=80
set updatetime=300

if &compatible
  set nocompatible
end

" Open vim-plug without a vertical split
let g:plug_window='enew'

call plug#begin('~/.vim/plugged')
  " LSP
  Plug 'neovim/nvim-lspconfig'

  " Completion
  Plug 'hrsh7th/cmp-nvim-lsp'
  Plug 'hrsh7th/cmp-buffer'
  Plug 'hrsh7th/cmp-path'
  Plug 'hrsh7th/cmp-cmdline'
  Plug 'hrsh7th/nvim-cmp'
  Plug 'hrsh7th/vim-vsnip'
  Plug 'hrsh7th/vim-vsnip-integ'

  " Treesitter
  Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
  Plug 'nvim-treesitter/playground'
  Plug 'RRethy/nvim-treesitter-endwise'

  " Fuzzy-finding :Ag, :Commits, :Files
  Plug '/opt/homebrew/opt/fzf'
  Plug 'junegunn/fzf.vim'

  " :help ale
  Plug 'dense-analysis/ale'

  " :help projectionist, .projections.json, :A
  Plug 'tpope/vim-projectionist'

  " :TestFile, :TestNearest
  Plug 'vim-test/vim-test'

  " Comment/uncomment lines and selections with <gcc>
  Plug 'tomtom/tcomment_vim'

  " Filesystem, :Rename, :Git blame
  Plug 'pbrisbin/vim-mkdir'
  Plug 'tpope/vim-eunuch'
  Plug 'tpope/vim-fugitive'

  " Alignment, auto pairs, auto tags
  Plug 'alvan/vim-closetag'
  Plug 'windwp/nvim-autopairs'

  " Frontends
  Plug 'leafgarland/typescript-vim'
  Plug 'mxw/vim-jsx'
  Plug 'pangloss/vim-javascript'

  " Backends
  Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
  Plug 'tpope/vim-rails'
  Plug 'vim-ruby/vim-ruby'
call plug#end()

" When reading a buffer, jump to last known cursor position except for
" commit messages, when position is invalid, or inside an event handler.
augroup lastcursorposition
  autocmd!

  autocmd BufReadPost *
    \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif
augroup END

" Lint with ALE
augroup ale
  autocmd!

  autocmd VimEnter *
    \ let g:ale_lint_on_enter = 1 |
    \ let g:ale_lint_on_text_changed = 0
augroup END

" Disable spelling by default, enable per-filetype
autocmd BufRead setlocal nospell

" Fuzzy-find files
nnoremap <C-p> :Files<CR>
let g:fzf_layout = { 'window': { 'width': 0.95, 'height': 0.9 } }

" Search file contents
nnoremap \ :Ag<SPACE>
set grepprg=ag\ --nogroup\ --nocolor

" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

" Switch between the last two files
nnoremap <Leader><Leader> <C-^>

" Run tests https://github.com/vim-test/vim-test#kitty-strategy-setup
nnoremap <silent> <Leader>t :TestFile<CR>
nnoremap <silent> <Leader>s :TestNearest<CR>
let g:test#strategy = "neovim"
let g:test#neovim#start_normal = 1
let g:test#echo_command = 0

" Move between windows
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Colors
hi clear

if exists("syntax_on")
  syntax reset
endif

" Delegate most highlighting decisions to Treesitter
" https://neovim.io/doc/user/treesitter.html#treesitter-highlight

" See highlight group under cursor
" :TSHighlightCapturesUnderCursor

" Show all syntax groups
" :so $VIMRUNTIME/syntax/hitest.vim

" Dim, sync w/ shell/kitty.conf background
hi SignColumn                           guibg=#191e2d

" White
hi Identifier            guifg=#ffffff
hi Keyword               guifg=#ffffff

" Light gray
hi Comment               guifg=#999999
hi Cursor                guifg=#999999
hi Ignore                guifg=#999999
hi LineNr                guifg=#999999
hi NonText               guifg=#999999
hi Operator              guifg=#999999
hi PmenuSel              guifg=#ffffff  guibg=#999999
hi PmenuThumb            guifg=#ffffff  guibg=#999999
hi Special               guifg=#999999
hi StatusLine            guifg=#999999
hi TabLine               guifg=#ffffff  guibg=#999999
hi VertSplit             guifg=#999999

" Yellow
hi DiagnosticWarn        guifg=#ffd080
hi Type                  guifg=#ffd080
hi RedrawDebugClear      guifg=#ffd080  guibg=#191e2d
hi Search                               guibg=#ffd080
hi String                guifg=#ffd080
hi WildMenu                             guibg=#d7005f

" Purple
hi @conditional          guifg=#9664c8
hi Directory             guifg=#9664c8
hi Function              guifg=#9664c8
hi PreProc               guifg=#9664c8

" Pink
hi @diff.minus           guifg=#d7005f
hi @symbol               guifg=#d7005f
hi @text.diff.delete     guifg=#d7005f
hi Boolean               guifg=#d7005f
hi ColorColumn                          guibg=#d7005f
hi Constant              guifg=#d7005f
hi DiagnosticError       guifg=#d7005f
hi DiffText                             guibg=#d7005f
hi Error                                guibg=#d7005f
hi ErrorMsg                             guibg=#d7005f
hi Number                guifg=#d7005f
hi NvimInternalError     guifg=#ffffff  guibg=#d7005f
hi Pmenu                                guibg=#d7005f
hi PreProc               guifg=#d7005f
hi RedrawDebugRecompose                 guibg=#d7005f
hi Statement             guifg=#d7005f
hi Title                 guifg=#d7005f
hi WarningMsg            guifg=#d7005f

" Green
hi @diff.plus            guifg=#64c88e
hi @text.diff.add        guifg=#64c88e
