#!/usr/bin/env sh

# Run this script to generate a Netlify-compatible binary.

set -ex

go get -t -d -v github.com/mitchellh/gox
(
  cd cmd/eng
  gox -osarch="linux/amd64"
  mv eng_linux_amd64 "$OK/blog/eng"
)
