#!/usr/bin/env bash
#
# validates that the project is clean of formatting and vet errors.
# symlink as .git/hooks/pre-commit to use as a pre-commit check.
#

function checkfmt() {
  gofiles=$(find . ! -path "*/_*" -name "*.go" | grep -Fv "./vendor/")
  [ -z "$gofiles" ] && return 0

  unformatted=$(gofmt -l $gofiles)
  [ -z "$unformatted" ] && return 0

  echo >&2 "Go files must be formatted with gofmt. Please run:"
  for filename in $unformatted; do
    echo >&2 "  gofmt -w $filename"
  done

  return 1
}

function checkvet() {
  unvetted=$(go vet $(go list ./... | grep -v /vendor/) 2>&1 | grep -v "exit status")
  [ -z "$unvetted" ] && return 0

  echo >&2 "Go files must be vetted. Check these problems:"
  IFS=$'\n'
  for line in $unvetted; do
    echo >&2 "  $line"
  done
  unset IFS

  return 1
}

checkfmt || fail=yes
checkvet || fail=yes

[ -z "$fail" ] || exit 1
