# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.6.1'

gem 'dotenv'
gem 'html_to_plain_text'
gem 'sinatra'

group :development do
  gem 'rubocop', '0.53'
end

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'webmock'
end
