# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.6.1'

gem 'activerecord'
gem 'dotenv'
gem 'pg'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'

group :development do
  gem 'rubocop', '0.53'
end

group :test do
  gem 'rspec'
  gem 'webmock'
end
