let mapleader = " "   " Spacebar

set autoindent
set autowrite         " Automatically :write before running commands
set backspace=2       " Backspace deletes like most programs in insert mode
set colorcolumn=+1
set complete+=kspell  " Include spellfile in completion results
set diffopt+=vertical " Always use vertical diffs
set expandtab
set exrc              " http://andrew.stwrt.ca/posts/project-specific-vimrc/
set history=50
set incsearch
set laststatus=2      " Always display status line
set list listchars=tab:»·,trail:·,nbsp:·
set nobackup
set nojoinspaces      " Use one space, not two, after punctuation
set noswapfile
set nowritebackup
set number
set numberwidth=5
set ruler             " Ahow cursor position all the time
set shiftround
set shiftwidth=2
set showcmd           " Display incomplete commands
set splitbelow
set splitright
set tabstop=2
set textwidth=80

if &compatible
  set nocompatible
end

call plug#begin('~/.vim/plugged')
  Plug '/usr/local/opt/fzf'
  Plug 'AndrewRadev/splitjoin.vim'
  Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
  Plug 'janko-m/vim-test'
  Plug 'junegunn/fzf.vim'
  Plug 'junegunn/vim-easy-align'
  Plug 'leafgarland/typescript-vim'
  Plug 'mxw/vim-jsx'
  Plug 'nicholaides/words-to-avoid.vim'
  Plug 'pangloss/vim-javascript'
  Plug 'pbrisbin/vim-mkdir'
  Plug 'sbdchd/neoformat'
  Plug 'tpope/vim-endwise'
  Plug 'tpope/vim-eunuch'
  Plug 'tpope/vim-fugitive'
  Plug 'tpope/vim-projectionist'
  Plug 'tpope/vim-rails'
  Plug 'vim-ruby/vim-ruby'
  Plug 'vim-scripts/tComment'
  Plug 'w0rp/ale'
call plug#end()

augroup vimrcEx
  autocmd!

  " When editing a file, always jump to the last known cursor position.
  " Don't do it for commit messages, when the position is invalid, or when
  " inside an event handler (happens when dropping a file on gvim).
  autocmd BufReadPost *
    \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif

  " ALE linting events
  set updatetime=1000
  let g:ale_lint_on_text_changed = 0
  autocmd CursorHold * call ale#Lint()
  autocmd CursorHoldI * call ale#Lint()
  autocmd InsertEnter * call ale#Lint()
  autocmd InsertLeave * call ale#Lint()
augroup END

" Use fzf for finding files
nmap <C-p> :Files<CR>

" Use ag for searching files
nmap \ :Ag<SPACE>
set grepprg=ag\ --nogroup\ --nocolor

" Bind K to grep word under cursor
nmap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

" Tab completion
" will insert tab at beginning of line,
" will use completion if not at beginning
set wildmode=list:longest,list:full
function! InsertTabWrapper()
    let col = col('.') - 1
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<Tab>"
    else
        return "\<C-p>"
    endif
endfunction
inoremap <Tab> <C-r>=InsertTabWrapper()<CR>
inoremap <S-Tab> <C-n>

" Switch between the last two files
nnoremap <leader><leader> <C-^>

" vim-test mappings
nnoremap <silent> <Leader>t :TestFile<CR>
nnoremap <silent> <Leader>s :TestNearest<CR>
nnoremap <silent> <Leader>l :TestLast<CR>

" Treat <li> and <p> tags like the block tags they are
let g:html_indent_tags = 'li\|p'

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Exclude JavaScript files in :Rtags via rails.vim due to warnings when parsing
let g:Tlist_Ctags_Cmd="ctags --exclude='*.js'"

" Index ctags from any project, including those outside Rails
function! ReindexCtags()
  let l:ctags_hook = '$(git rev-parse --show-toplevel)/.git/hooks/ctags'

  if exists(l:ctags_hook)
    exec '!'. l:ctags_hook
  else
    exec "!ctags -R ."
  endif
endfunction

nmap <Leader>ct :call ReindexCtags()<CR>

" Colors
hi clear
if version > 580
  if exists("syntax_on")
    syntax reset
  endif
endif

hi ColorColumn  ctermbg=253 cterm=NONE
hi Comment      ctermfg=248 cterm=NONE
hi Constant     ctermfg=30  cterm=NONE
hi Cursor       ctermfg=231 ctermbg=238 cterm=NONE
hi CursorColumn ctermbg=253 cterm=NONE
hi CursorLine   ctermbg=253 cterm=NONE
hi CursorLineNr ctermfg=250 ctermbg=253 cterm=NONE
hi DiffAdd      ctermfg=22  ctermbg=194 cterm=NONE
hi DiffChange   ctermbg=255 cterm=NONE
hi DiffDelete   ctermfg=252 ctermbg=224 cterm=NONE
hi DiffText     ctermfg=17  ctermbg=189 cterm=NONE
hi Directory    ctermfg=88  cterm=NONE
hi Error        ctermfg=231 ctermbg=196 cterm=NONE
hi Folded       ctermfg=244 ctermbg=255 cterm=NONE
hi Function     ctermfg=88  cterm=BOLD
hi Identifier   ctermfg=31  cterm=NONE
hi Ignore       ctermfg=244 cterm=NONE
hi IncSearch    ctermfg=16  ctermbg=189 cterm=NONE
hi Label        ctermfg=16  cterm=BOLD
hi LineNr       ctermfg=250 ctermbg=255 cterm=NONE
hi MatchParen   ctermfg=16  ctermbg=189 cterm=NONE
hi ModeMsg      ctermfg=88  cterm=NONE
hi MoreMsg      ctermfg=88  cterm=NONE
hi NonText      ctermfg=244 ctermbg=255 cterm=NONE
hi Normal       ctermfg=16  ctermbg=231 cterm=NONE
hi Number       ctermfg=30  cterm=NONE
hi Pmenu        ctermfg=231 ctermbg=244 cterm=BOLD
hi PmenuSbar    ctermfg=238 ctermbg=16  cterm=NONE
hi PmenuSel     ctermfg=16  ctermbg=189 cterm=NONE
hi PmenuThumb   ctermfg=248 ctermbg=248 cterm=NONE
hi PreProc      ctermfg=247 cterm=BOLD
hi Search       ctermfg=16  ctermbg=189 cterm=NONE
hi Special      ctermfg=28  cterm=BOLD
hi SpecialKey   ctermfg=231 ctermbg=196 cterm=NONE
hi Statement    ctermfg=16  cterm=BOLD
hi StatusLine   ctermfg=238 ctermbg=250 cterm=BOLD
hi StatusLineNC ctermfg=250 ctermbg=255 cterm=NONE
hi StorageClass ctermfg=16  cterm=BOLD
hi String       ctermfg=161 cterm=NONE
hi Structure    ctermfg=16  cterm=BOLD
hi TabLine      ctermfg=238 ctermbg=253 cterm=NONE
hi TabLineFill  ctermfg=238 ctermbg=253 cterm=NONE
hi TabLineSel   ctermfg=238 cterm=BOLD
hi Title        ctermfg=203 cterm=NONE
hi Todo         ctermfg=231 ctermbg=196 cterm=UNDERLINE
hi Todo         ctermfg=231 ctermbg=88  cterm=BOLD
hi Type         ctermfg=60  cterm=BOLD
hi TypeDef      ctermfg=16  cterm=BOLD
hi Underlined   ctermfg=16  cterm=UNDERLINE
hi VertSplit    ctermfg=250 ctermbg=250 cterm=NONE
hi Visual       ctermfg=231 ctermbg=61  cterm=NONE
hi VisualNOS    ctermfg=231 ctermbg=24  cterm=NONE
hi WarningMsg   ctermfg=203 cterm=NONE
hi WildMenu     ctermfg=111 ctermbg=60  cterm=NONE
hi cucumberTags ctermfg=236 ctermbg=227 cterm=BOLD
hi htmlTagN     cterm=BOLD
hi rubySymbol   ctermfg=89  cterm=NONE

hi link rubyStringDelimiter String
