#!/bin/bash
#
# hook to add go lint warnings to commit messages

case "$2,$3" in
  ,) ;;        # git commit
  commit,*) ;; # git commit --amend

  *)
    exit 0 ;;
esac

function checklint() {
  unlinted=$(golint $* 2>&1)
  [ -z "$unlinted" ] && return 0

  echo >&2 "Go files should be linted. Consider these warnings:"
  IFS=$'\n'
  for line in $unlinted; do
    echo >&2 "  $line"
  done
  unset IFS

  return 1
}

# find all changed go files
gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '.go$')
[ -z "$gofiles" ] && exit 0

unlinted=$(checklint $gofiles 2>&1)
[ -z "$unlinted" ] && exit 0

# prefix each line with "# "
unlinted=$(echo "$unlinted" | sed 's/^/# /')

# append a backslash to each line
unlinted=$(echo "$unlinted" | sed 's/$/\\/')

# add lint messages to commit message
sed -i '' "1i \\
$unlinted
" "$1"
